version: "3"
services:
  starsiegetribes:
    stdin_open: true
    tty: true
    container_name: "starsiegetribes"
    build:
      context: "./"
    volumes:
      - "/var/containers/tribes:/data"
    environment:
      - ServerHostName=Play with bots
      - InstallRenegades=1
      - InstallSpoonbot=1
    network_mode: "host"

