version: "3"
services:
  starsiegetribes:
    container_name: "starsiegetribes"
    build:
      context: "./"
    volumes:
      - "/var/containers/tribes:/data"
    network_mode: host
    environment:
      - ServerHostName="Play with bots"
    ports:
      - "28001:28001"

